Repository keystonejs/keystone-classic, pull requests merged in 2018-06, with the labels that each got.

#4601 Adding in the missing DayPicker-WeekdaysRow
  admin/public/styles/keystone.less
Labels: bug

#4662 show color swatch on color field
  fields/types/color/ColorField.js
  fields/types/color/colored-swatch.js
Labels: cosmetic

#4671 More README updates for v4
  README.md
Labels: documentation

#4680 Update GitHub issue/PR templates
  .github/ISSUE_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: meta

#4690 Fix #4686: CloudinaryImage(s) fields were incorrectly marked as deprecated
  fields/types/cloudinaryimage/Readme.md
  fields/types/cloudinaryimages/Readme.md
Labels: documentation

#4673 Provides a fix for a bug in Safari where XHR form submission fails wh…
  admin/client/App/screens/Item/components/EditForm.js
Labels: needs review
