Repository keystonejs/keystone-classic, pull requests merged in 2018-07, with the labels that each got.

#4692 Include keystone.version in startup message
  lib/core/start.js
Labels: cosmetic

#4689 Update part-4.md
  docs/Getting Started/Setting-Up/part-4.md
Labels: documentation

#4635 Smooth scroll speed adjustment for Admin UI
  admin/client/App/screens/Item/components/EditForm.js
Labels: cosmetic, needs review

#4700 Upgrade qs to 6.5.2
  package.json
Labels: dependencies

#4256 Update z-index of color chooser
  fields/types/color/ColorField.js
Labels: cosmetic, needs review

#4709 Fix #4708: Update Getting Started page
  docs/Getting Started/index.md
Labels: documentation

#4455 Minor fixes and improvements to the location field type
  fields/types/location/LocationType.js
Labels: enhancement, needs review

#4704 Update to multer 1.3.1 and automatically clean uploaded files
  admin/server/app/createDynamicRouter.js
  index.js
  lib/uploads.js
  package.json
  server/bindBodyParser.js
  yarn.lock
Labels: dependencies, enhancement

#4721 Reviewed Getting Started documentation
  docs/Getting Started/Setting-Up/part-1.md
  docs/Getting Started/Setting-Up/part-2.md
  docs/Getting Started/Setting-Up/part-3.md
  docs/Getting Started/Setting-Up/part-4.md
  docs/Getting Started/yo-generator.md
  docs/api/Field/Underscore-Methods.md
  docs/api/List/add.md
  docs/api/List/index.md
  docs/api/List/model.md
  docs/api/List/options.md
  docs/api/List/register.md
  docs/api/List/update-item.md
  docs/api/Methods/closeDatabaseConnection.md
  docs/api/Methods/get.md
  docs/api/Methods/index.md
  docs/api/Methods/init.md
  docs/api/Methods/list.md
  docs/api/Methods/middleware.md
  docs/api/Methods/openDatabaseConnection.md
  docs/api/Methods/paginate.md
  docs/api/Methods/pre.md
  docs/api/Methods/set.md
  docs/api/Methods/start.md
  docs/api/Methods/update-handler.md
  docs/guides/index.md
  docs/guides/v0.3-to-v4.0-Upgrade-Guide.md
Labels: documentation

#4728 FIxing broken links in README.md
  README.md
Labels: cosmetic

#4746 Fixed a typo in Project-Options.md
  docs/documentation/Configuration/Project-Options.md
Labels: documentation

#4743 Link "What's New" to 4.x release history
  website/src/pages/components/home/Hero.js
Labels: documentation
